[package]
name = "lab1_maze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
log = "0.4.20"
#bitflags = "2.4.1"
enumflags2 = "0.7.8"
svg = "0.14.0"
image = "0.24.7"
